
service: go-serverless
frameworkVersion: '>=1.28.0 <2.0.0'



provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  stage: dev
  environment:
    SERVICE_NAME: ${self.service}
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  graphql:
    handler: bin/graphql
    events:
      - http:
          path: graphql-lambda
          method: post

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'api.denemetest.com'
    basePath: 'home'
    stage: ${self.provider.stage}
    createRoute53Record: false