
service: go-serverless
frameworkVersion: '>=1.28.0 <2.0.0'

.commonconfig: &commonconfig
  ${file(../../shared/common/serverless.common.yml):commonResources}

custom: ${file(../../shared/common/serverless.common.yml):custom}

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  runtime: go1.x
  region: ${self:custom.region}
  stage: dev
  tracing:
    apiGateway: true
    lambda: true
  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
  iamRoleStatements:
    - ${file(../../shared/common/serverless.common.yml):lambdaPolicyXray}


functions:
  graphql:
    handler: bin/graphql
    events:
      - http:
          path: graphql-lambda
          method: post


resources:
  - *commonconfig
  #  Create Base API, rest of the services depends on this service, deploy first
  - ${file(../../shared/resources/agw/base_api.yml)}