
service: go-serverless
frameworkVersion: '>=1.28.0 <2.0.0'


custom: ${file(../../shared/common/serverless.common.yml):custom}

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  runtime: go1.x
  region: ${self:custom.region}
  stage: dev
  tracing:
    apiGateway: true
    lambda: true
  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
  iamRoleStatements:
    - ${file(../../shared/common/serverless.common.yml):lambdaPolicyXray}


functions:
  graphql:
    handler: bin/graphql
    events:
      - http:
          path: graphql-lambda
          method: post


resources:
  - $(../../shared/resources/api-gateway-errors.yml)}
  - Outputs:
      ApiGatewayRestApiId:
        Value:
          Ref: RibbonExRestApi
        Export:
          Name: ${self:custom.stage}-ExtApiGatewayRestApiId
      ApiGatewayRestApiRootResourceId:
        Value:
          Fn::GetAtt:
            - RibbonExRestApi
            - RootResourceId
        Export:
          Name: ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId