
service: world
frameworkVersion: '>=1.28.0 <2.0.0'

.commonconfig: &commonconfig
  ${file(../../shared/common/serverless.common.yml):commonResources}

custom: ${file(../../shared/common/serverless.common.yml):custom}

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

provider:
  name: aws
  runtime: go1.x
  region: ${self:custom.region}
  profile: ${self:custom.profiles.${self:provider.stage}}
  stage: dev
  tracing:
    lambda: true
  apiGateway:
    ${file(../../shared/resources/agw/agwId.yml):apiGateway}
  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
  iamRoleStatements:
    - ${file(../../shared/common/serverless.common.yml):lambdaPolicyXray}


functions:
  hello:
    handler: bin/world
    events:
      - http:
          path: world
          method: get

resources:
  - *commonconfig