service: world

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x


package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
