service: world

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  stage: dev


package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ribbonex.com
    basePath: world
    stage: dev
    createRoute53Record: true