
service: hello

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'ribbonex.com'
    basePath: 'hello'
    stage: "dev"
    createRoute53Record: true