name: Go

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install Serverless Plugins
      run: sudo npm i serverless -g

    - name: Build
      run: bash ./scripts/build-deploy.sh build ${{ github.event.before }} ${{ github.sha }}


    - name: Configure-Creds
      run: ./scripts/configure-creds.sh ${{secrets.AWS_ACCESS_KEY_ID}} ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Serverless Deploy
      run: sudo ./scripts/build-deploy.sh deploy ${{ github.event.before }} ${{ github.sha }}

