name: Create Realase
on:
  push:
    tags:
      - 'v*'


jobs:
  create_realase:
    needs: buildAndDeploy
    name: Create Realase
    runs-on: ubunti-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
