name: Labeller
on:
  - pull_request


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Label Pull Request
      uses: actions/labeler@v2
      with:
        repo-token: "${{secrets.GITHUB_TOKEN}}"
        configuration-path: .github/actions/pull/labels.yml
