name: Labeller
on:
  - pull_request


jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Auto Label Pull Request
      uses: actions/labeler@v2
      with:
        repo-token: "${{secrets.GITHUB_TOKEN}}"
        configuration-path: .github/actions/pull/labels.yml
    - name: Install GolangCi
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.26.0

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Lint
      run: echo "::set-output name=lintOutput::$(./bin/golangci-lint run)"
      id: lint

    - name: Lint
      run: echo ${{steps.lint.outputs.lintOutput}}
      id: lint2
      
    - name: Comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "```${{steps.lint.outputs.lintOutput}}```"
        check_for_duplicate_msg: false